YAHA PE HAM FORM KO USE KR RHEHHAI  API CALL KRME KE LIYE 

API CALL FOR RESTAURENT
    MAKE FUNCTION FOR POST API DATA 
    IMPORT SERVICE IN ADD RESTO COMPONENT   (API  ka result cherck)
    CALL FUNCTION
    CHECK RESULT AND LISTING 